# Generated by Django 4.1 on 2022-08-13 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='history',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
